SET HEADING OFF
SET VERIFY OFF
SET FEEDBACK OFF

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER {DBA_ID} IDENTIFIED BY {PASSWORD}
  DEFAULT TABLESPACE DSDATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DSDATA
QUOTA UNLIMITED ON DSINDX
QUOTA UNLIMITED ON RTDATA
QUOTA UNLIMITED ON RTINDX
QUOTA UNLIMITED ON RTBLOB
QUOTA UNLIMITED ON WKDATA
QUOTA UNLIMITED ON WKINDX
QUOTA UNLIMITED ON WKBLOB
;

GRANT CREATE PROCEDURE TO {DBA_ID};
GRANT CREATE PUBLIC SYNONYM TO {DBA_ID};
GRANT CREATE SEQUENCE TO {DBA_ID};
GRANT CREATE SESSION TO {DBA_ID};
GRANT CREATE SYNONYM TO {DBA_ID};
GRANT CREATE TABLE TO {DBA_ID};
GRANT CREATE TRIGGER TO {DBA_ID};
GRANT CREATE TYPE TO {DBA_ID};
GRANT CREATE VIEW TO {DBA_ID};

GRANT DBA TO {DBA_ID};
GRANT IMP_FULL_DATABASE TO {DBA_ID};
GRANT EXP_FULL_DATABASE TO {DBA_ID};

exit;