---
--- CREATE TABLE: HELLO_WORLD
---
CREATE TABLE HELLO_WORLD
(
	HW_PGUID CHAR(32) NOT NULL,
	SI_SGUID CHAR(32) NOT NULL, -- Soft reference to EDM Service Instance
	NAME VARCHAR2(256) NOT NULL,
	PRIMARY KEY (HW_PGUID)
)
;

---
--- CREATE TABLE: HELLO_MOON
---
CREATE TABLE HELLO_MOON
(
	HM_PGUID CHAR(32) NOT NULL,
	HW_PGUID CHAR(32),
	NAME VARCHAR2(256),
	PRIMARY KEY (HM_PGUID)
)
;

---
--- CREATE FOREIGN KEY CONSTRAINT: Relation_1
---
ALTER TABLE HELLO_MOON ADD 
	FOREIGN KEY (HW_PGUID)
		REFERENCES HELLO_WORLD (HW_PGUID)
;

EXIT;